import "./globals.css";
import { Header } from "@/components/Header";
import { ChakraProvider, Flex } from "@chakra-ui/react";
import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";

const font = Noto_Sans_JP({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={font.className}>
        <ChakraProvider>
          <Flex flexDirection={"column"} align={"center"} minH={"100vh"}>
            <Header />
            {children}
          </Flex>
        </ChakraProvider>
      </body>
    </html>
  );
}
